name: 'Need Help'
description: 'If you need any assistance, write it here.'
labels: ['help']
title: '[help]'
body:
  - type: markdown
    attributes:
      value: |
        Please provide a searchable summary of the issue in the title above ⬆️.

        We will respond to your query soon! ❤️
  - type: checkboxes
    attributes:
      label: Duplicates
      description: Please [search the history](https://github.com/mui/material-ui/issues) to see if an issue already exists for the same problem.
      options:
        - label: 'I have searched the existing issues'
          required: true
  - type: input
    id: 'page-url'
    attributes:
      label: 'Related package'
      description: 'Which package of the documentation is this about?'
      placeholder: ''
    validations:
      required: true
  - type: textarea
    id: 'issue-description'
    attributes:
      label: 'Issue description'
      description: |
        Let us know what went wrong when you were using this documentation and what we could do to improve it.
      value: |
        I was looking for ... and it appears that ...
  - type: textarea
    id: 'context'
    attributes:
      label: 'Context 🔦'
      description: 'What are you trying to accomplish? What brought you to this page? Your context can help us to come up with solutions that benefit the community as a whole.'
